package:
  name: ruby3.4-train
  version: "3.14.1"
  epoch: 0
  description: Transport Interface to unify communication over SSH, WinRM, and friends.
  copyright:
    - license: Ruby
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby${{vars.rubyMM}}-addressable
      - ruby${{vars.rubyMM}}-net-ssh
      - ruby${{vars.rubyMM}}-train-core

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: fd87e91ff17e1ac3e7075d710166b7a1b5667f60
      repository: https://github.com/inspec/train/
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: train

update:
  enabled: true
  github:
    identifier: inspec/train
    strip-prefix: v
    use-tag: true

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM

subpackages:
  - name: ruby${{vars.rubyMM}}-train-core
    dependencies:
      runtime:
        - ruby${{vars.rubyMM}}-chef-utils
        - ruby${{vars.rubyMM}}-ffi
        - ruby${{vars.rubyMM}}-mixlib-shellout
        - ruby${{vars.rubyMM}}-net-scp
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}-core
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}-core
          version: ${{package.version}}
      - uses: ruby/clean

test:
  environment:
    contents:
      packages:
        - build-base
        - ruby-${{vars.rubyMM}}-dev
        - ruby${{vars.rubyMM}}-bundler
        - ruby${{vars.rubyMM}}-json
        - ruby${{vars.rubyMM}}-psych
        - ruby${{vars.rubyMM}}-stringio
  pipeline:
    - runs: |
        # Test that our installed package is importable
        ruby -e "require 'train'"
    - uses: git-checkout
      with:
        expected-commit: fd87e91ff17e1ac3e7075d710166b7a1b5667f60
        repository: https://github.com/inspec/train
        tag: v${{package.version}}
    - runs: |
        # Run upstream tests: against the repo's code not our installed
        # package, but at least find out if we have incompatibilities
        bundle install
        bundle exec rake test
