package:
  name: ruby3.4-sslshake
  version: "1.3.0"
  epoch: 0
  description: Ruby library for pure SSL/TLS handshake testing
  copyright:
    - license: MPL-2.0
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: cf26d6d8bd397e594acb5ce9dd96b67ed63269c7
      repository: https://github.com/arlimus/sslshake
      tag: ${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: sslshake

update:
  enabled: true
  github:
    identifier: arlimus/sslshake
    use-tag: true

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM

test:
  environment:
    contents:
      packages:
        - build-base
        - ruby-${{vars.rubyMM}}-dev
        - ruby${{vars.rubyMM}}-bundler
        - ruby${{vars.rubyMM}}-json
        - ruby${{vars.rubyMM}}-psych
        - ruby${{vars.rubyMM}}-stringio
  pipeline:
    - runs: |
        # Test that our installed package is importable
        ruby -e "require '${{vars.gem}}'"
#    - uses: git-checkout
#      with:
#        expected-commit: 5fa6a0cf89a6d63ffde704990b2437720da89d66
#        repository: https://github.com/net-ssh/net-ssh
#        tag: v${{package.version}}
#    - runs: |
#        # Run upstream tests: against the repo's code not our installed
#        # package, but at least find out if we have incompatibilities
#        bundle install
#        bundle exec rake test
