package:
  name: ruby3.4-unicode-emoji
  version: "4.2.0"
  epoch: 0
  description: Up-to-date Emoji Regex and Data in Ruby
  copyright:
    - license: MIT
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: beff6fe9a2935a8c1bd417ae7e775c685d514f2e
      repository: https://github.com/janlelis/unicode-emoji
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: unicode-emoji

update:
  enabled: true
  github:
    identifier: janlelis/unicode-emoji
    strip-prefix: v
    use-tag: true

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM

test:
  environment:
    contents:
      packages:
        - build-base
        - ruby-${{vars.rubyMM}}-dev
        - ruby${{vars.rubyMM}}-bundler
        - ruby${{vars.rubyMM}}-json
        - ruby${{vars.rubyMM}}-psych
        - ruby${{vars.rubyMM}}-stringio
  pipeline:
    - runs: |
        # Test that our installed package is importable
        ruby -e "require 'unicode/emoji'"
#    - uses: git-checkout
#      with:
#        expected-commit: 5fa6a0cf89a6d63ffde704990b2437720da89d66
#        repository: https://github.com/net-ssh/net-ssh
#        tag: v${{package.version}}
#    - runs: |
#        # Run upstream tests: against the repo's code not our installed
#        # package, but at least find out if we have incompatibilities
#        bundle install
#        bundle exec rake test
