package:
  name: ruby3.4-unicode_utils
  version: "1.4.0"
  epoch: 0
  description: Unicode algorithms for Ruby
  copyright:
    - license: BSD-2-Clause
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 52e54c99c1ebf846528f26cda63478c94d860244
      repository: https://github.com/lang/unicode_utils
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: unicode_utils

update:
  enabled: true
  github:
    identifier: lang/unicode_utils
    strip-prefix: v
    use-tag: true

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM

test:
  environment:
    contents:
      packages:
        - build-base
        - ruby-${{vars.rubyMM}}-dev
        - ruby${{vars.rubyMM}}-bundler
        - ruby${{vars.rubyMM}}-json
        - ruby${{vars.rubyMM}}-psych
        - ruby${{vars.rubyMM}}-stringio
  pipeline:
    - runs: |
        # Test that our installed package is importable
        ruby -e "require '${{vars.gem}}'"
#    - uses: git-checkout
#      with:
#        expected-commit: 5fa6a0cf89a6d63ffde704990b2437720da89d66
#        repository: https://github.com/net-ssh/net-ssh
#        tag: v${{package.version}}
#    - runs: |
#        # Run upstream tests: against the repo's code not our installed
#        # package, but at least find out if we have incompatibilities
#        bundle install
#        bundle exec rake test
