package:
  name: ruby3.4-net-ssh
  version: "7.3.0"
  epoch: 0
  description: Pure Ruby implementation of an SSH (protocol 2) client
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 5fa6a0cf89a6d63ffde704990b2437720da89d66
      repository: https://github.com/net-ssh/net-ssh
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: net-ssh

update:
  enabled: true
  github:
    identifier: net-ssh/net-ssh
    strip-prefix: v
    use-tag: true

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM

test:
  environment:
    contents:
      packages:
        - build-base
        - ruby-${{vars.rubyMM}}-dev
        - ruby${{vars.rubyMM}}-bundler
        - ruby${{vars.rubyMM}}-json
        - ruby${{vars.rubyMM}}-psych
        - ruby${{vars.rubyMM}}-stringio
  pipeline:
    - runs: |
        # Test that our installed package is importable
        ruby -e "require 'net/ssh'"
    - uses: git-checkout
      with:
        expected-commit: 5fa6a0cf89a6d63ffde704990b2437720da89d66
        repository: https://github.com/net-ssh/net-ssh
        tag: v${{package.version}}
    - runs: |
        # Run upstream tests: against the repo's code not our installed
        # package, but at least find out if we have incompatibilities
        bundle install
        bundle exec rake test
