# depending on how much of chef's gems we need to use and support, we
# may just want one omnibus source yaml
package:
  name: ruby3.4-chef-utils
  version: "19.1.135"
  epoch: 0
  description: Basic utility functions for Core Chef Infra development
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby${{vars.rubyMM}}-concurrent-ruby

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 059a058c4e8016f33da75a673c1746b6d68aa54c
      repository: https://github.com/chef/chef/
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      dir: chef-utils
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      dir: chef-utils
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: chef-utils

update:
  enabled: true
  github:
    identifier: chef/chef
    strip-prefix: v
    use-tag: true

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM

test:
  environment:
    contents:
      packages:
        - build-base
        - ruby-${{vars.rubyMM}}-dev
        - ruby${{vars.rubyMM}}-bundler
        - ruby${{vars.rubyMM}}-json
        - ruby${{vars.rubyMM}}-psych
        - ruby${{vars.rubyMM}}-stringio
  pipeline:
    - runs: |
        # Test that our installed package is importable
        ruby -e "require 'chef-utils'"
