package:
  name: ruby3.4-tomlrb
  version: "2.0.4"
  epoch: 0
  description: A Racc based TOML parser
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby${{vars.rubyMM}}-tomlrb

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 263d97f493bd7049a9779de7c95abe27a59260b0
      repository: https://github.com/fbernier/tomlrb
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: tomlrb

update:
  enabled: true
  github:
    identifier: fbernier/tomlrb
    strip-prefix: v
    use-tag: true

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM

test:
  environment:
    contents:
      packages:
        - build-base
        - ruby-${{vars.rubyMM}}-dev
        - ruby${{vars.rubyMM}}-bundler
        - ruby${{vars.rubyMM}}-json
        - ruby${{vars.rubyMM}}-psych
        - ruby${{vars.rubyMM}}-stringio
  pipeline:
    - runs: |
        # Test that our installed package is importable
        ruby -e "require 'tomlrb'"
    - uses: git-checkout
      with:
        expected-commit: 263d97f493bd7049a9779de7c95abe27a59260b0
        repository: https://github.com/fbernier/tomlrb
        tag: v${{package.version}}
    - runs: |
        # Run upstream tests: against the repo's code not our installed
        # package, but at least find out if we have incompatibilities
        bundle install
        bundle exec rake test
